apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: kloud-metrics
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - grafana.kloud.rche.moe
      secretName: grafana-tls
  rules:
    - host: grafana.kloud.rche.moe
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
