server {
    listen 80 default_server;
    server_name ako.pet;
    root /usr/share/nginx/html;

    location = /healthz {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "ok\n";
    }

    location = / {
        add_header Cache-Control "no-store";
        try_files /ako.html =404;
    }

    location /assets/ {
        add_header Cache-Control "public, max-age=31536000, immutable";
        try_files $uri =404;
    }

    location / {
        add_header Cache-Control "no-store";
        try_files $uri /ako.html;
    }
}

server {
    listen 80;
    server_name www.ako.pet;

    return 308 https://ako.pet$request_uri;
}

server {
    listen 80;
    server_name malkuth.moe;
    root /usr/share/nginx/html;

    location = /healthz {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "ok\n";
    }

    location = / {
        add_header Cache-Control "no-store";
        try_files /malkuth.html =404;
    }

    location /assets/ {
        add_header Cache-Control "public, max-age=31536000, immutable";
        try_files $uri =404;
    }

    location / {
        add_header Cache-Control "no-store";
        try_files $uri /malkuth.html;
    }
}

server {
    listen 80;
    server_name www.malkuth.moe;

    return 308 https://malkuth.moe$request_uri;
}
