apiVersion: v1
kind: PersistentVolume
metadata:
  name: blog-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /home/ch4n33/server-data/blog
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ["ch4n33-server"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-pvc
  namespace: kloud-apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: blog-pv
  resources:
    requests:
      storage: 1Gi
