---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wireguard-pv
spec:
  capacity:
    storage: 100Mi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/ch4n33/server-data/wireguard
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ["ch4n33-server"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wireguard-pvc
  namespace: kloud-vpn
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 100Mi
  volumeName: wireguard-pv
  storageClassName: ""
