---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-data-pv
spec:
  capacity:
    storage: 20Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/ch4n33/server-data/minecraft-server/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ["ch4n33-server"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-data-pvc
  namespace: kloud-apps
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
  volumeName: minecraft-data-pv
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-plugins-pv
spec:
  capacity:
    storage: 2Gi
  accessModes: ["ReadWriteOnce"]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /home/ch4n33/server-data/minecraft-server/plugins
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values: ["ch4n33-server"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-plugins-pvc
  namespace: kloud-apps
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
  volumeName: minecraft-plugins-pv
  storageClassName: ""
